syntax = "proto3";

package apexkey;

// The service definition.
service KVStore {
  // A simple Put/Get interface
  rpc Put (PutRequest) returns (PutResponse) {}
  rpc Get (GetRequest) returns (GetResponse) {}
  rpc Update (UpdateRequest) returns (UpdateResponse) {} 
  rpc Delete (DeleteRequest) returns (DeleteResponse) {}
}

message PutRequest {
  string key = 1;
  string value = 2;
}

message PutResponse {
  bool success = 1;
}

message GetRequest {
  string key = 1;
}

message GetResponse {
  string value = 1;
  bool found = 2;
}

message UpdateRequest {
  string key = 1;
  string value = 2;
}

message UpdateResponse {
  bool success = 1;
  string message = 2; // Useful to say "Key not found"
}

message DeleteRequest {
  string key = 1;
}

message DeleteResponse {
  bool success = 1;
}